### PR TITLE
Implements basic trivia view - fixes #9

### LINKED ISSUE #9: Trivia view

### PR DESCRIPTION
**Pull request by EricMFischer**

### CODE REVIEW

**Comment by cassiebeckley** [comment]
Looks good! :+1:

**Comment by hsadler** [comment]
+1

**Comment by cassiebeckley** [comment]
@EricMFischer - include the issue number that you're fixing in the future, so that merging the pull request will close the issue :wink:

**Comment by ntoscano** [comment]
+1

**Pull request merged**
