### PR TITLE
fixed #55 

### LINKED ISSUE #55: set up signIn/signUp pages

### PR DESCRIPTION
**Pull request by ntoscano**
User signup/signin still don't work. There's a weird error on the server side when you try to create a new user. I feel like it's really close to working, but I ran out of steam for the night. I submitted this pull request because I made a lot of changes that I feel we should all catch up to. 

Please look carefully at the changes I made before giving a "+1"; my concern is that I may have made changes to the architecture that aren't necessary,  don't make sense, or changed files that you guys are working on that would be difficult to merge together.

### CODE REVIEW

**Comment by hsadler** [comment]
Will check this tomorrow when there is time. Also, the Travis test failed on this pull request.

**Comment by ntoscano** [comment]
fixed test, but userAuth still has issues being added to the database

**Comment by cassiebeckley** [comment]
Looks good! :+1:

**Comment by EricMFischer** [comment]
Looks like some good additions. Let's review them more thoroughly on Thursday Nick. Enjoy yosemite

**Comment by hsadler** [comment]
+1

**Pull request merged**
