### PR TITLE
Tests for the trivia controller and factory

### PR DESCRIPTION
**Pull request by cassiebeckley**
From now on, we should probably include tests for each new feature we add, as we add it.

### CODE REVIEW

**Comment by hsadler** [comment]
+1

**Comment by ntoscano** [comment]
+1, any documentation I should read on how to do that?

**Comment by cassiebeckley** [comment]
Use the current tests as a reference. There's some docs about it on the [Angular website](https://docs.angularjs.org/guide/unit-testing).

**Comment by EricMFischer** [comment]
Excellente!

**Pull request merged**
