### PR TITLE
Add simple client-side tests - fixes #33

### LINKED ISSUE #33: Set up client-side testing

### PR DESCRIPTION
**Pull request by cassiebeckley**
We'll want to add some real tests eventually.

### CODE REVIEW

**Comment by cassiebeckley** [comment]
Don't merge this yet - I have to fix Travis.

**Comment by cassiebeckley** [comment]
This pull request should be good to merge now!

**Comment by hsadler** [comment]
+1

**Comment by ntoscano** [comment]
+1

**Comment by EricMFischer** [comment]
Looking good! :100: %

**Pull request merged**
