### PR TITLE
Made separate view pages, separate app modules, & set up ui routing and ui-view

### PR DESCRIPTION
**Pull request by EricMFischer**
you got pwned

### CODE REVIEW

**Comment by hsadler** [comment]
this Pull R has conflicts. Could you pull --rebase and submit again?

**Comment by ntoscano** [comment]
+1

**Comment by EricMFischer** [comment]
Lovely!

**Comment by hsadler** [comment]
+1

**Comment by cassiebeckley** [comment]
Looks wonderful! :+1:

**Pull request merged**
