### PR TITLE
fixed #29

### LINKED ISSUE #29: Set up a request handler
needed to add users to data base and serve trivia questions to the client

### PR DESCRIPTION
**Pull request by ntoscano**
created request handler and utility file for user authentication. responses to the client should be looked over by someone

### CODE REVIEW

**Comment by hsadler** [comment]
this is the first merge conflict with the main mayan-papaya repo, will touch base with yall about it

**Comment by ntoscano** [comment]
It was a conflict with the "package.JSON", I took care of it.

**Comment by hsadler** [comment]
looks good +1

**Comment by cassiebeckley** [comment]
Looks good! :+1:

**Comment by EricMFischer** [comment]
Great!

**Pull request merged**
