### PR TITLE
fixed #8

### LINKED ISSUE #8: Basic Angular set up

### PR DESCRIPTION
**Pull request by ntoscano**
Set up basic angular client skeleton

### CODE REVIEW

**Comment by cassiebeckley** [comment]
You might want to consider installing angular and angular-mocks using bower.

**Comment by hsadler** [comment]
+1

**Comment by EricMFischer** [comment]
Looking goooood

**Comment by cassiebeckley** [comment]
Okay, this is good for now - we can switch to using bower later.

**Pull request merged**
