### PR TITLE
fixed #90

### LINKED ISSUE #90: fix logout button

### PR DESCRIPTION
**Pull request by ntoscano**
I created the database for trivia questions, which stores only the question ID and the answer. The DB is set up to only check if the answer the user submitted is right, not to store the actual question. 

I still need to remove the answers from the response to the client, but I was having trouble figuring out how to use a promise for it, and it feels dirty to use a callback. 

currently I'm failing a jshint test for declaring a function inside a for-loop. If you guys have any idea how to fix this, please let me know. The error is the "findOne" function inside "addQuestion" in the "triviaController".

### CODE REVIEW

**Comment by hsadler** [comment]
I see that the addQuestion function is declaring an anonymous func inside the for loop, is that where the jshint is failing? David, is there a way to prevent jshint from enforcing that rule?

Nick, perhaps that anonymous callback could be pulled out and declared above the for loop in order to make the test pass...?

**Comment by ntoscano** [comment]
I forgot to change branches before working on the logout feature. It felt like it was going to take a significant chunk of time to figure out how to fix that. I decided to comment out the code that was failing the test and push the functional logout button to this branch.

**Comment by cassiebeckley** [comment]
:+1:

**Comment by hsadler** [comment]
+1

**Pull request merged**
