### PR TITLE
Endgameview functionality

### PR DESCRIPTION
**Pull request by EricMFischer**
Hey guys, so here are the things I'm still working on:

1) Potentially rendering the trivia.play.html (instead of the trivia.html view) view after you hit "play again" at the end of the round
2) Giving the user their final score at the end of the round

### CODE REVIEW

**Comment by cassiebeckley** [comment]
:+1:

**Comment by hsadler** [comment]
merge conflicts here. please rebase

**Comment by ntoscano** [comment]
+1, I'm waiting on this merge to start on issue #94

**Comment by EricMFischer** [comment]
resolved the merge conflicts

**Comment by hsadler** [comment]
+1, Thanks!

**Pull request merged**
