### PR TITLE
Timer

### PR DESCRIPTION
**Pull request by EricMFischer**
I implemented a timer 100 seconds long that will stop at 0. Lasts for the whole duration of the 10 question round. Still have to make it "end the game" once the timer runs out. That I'll work on tomorrow along with the endgame view that would pop up as well.

### CODE REVIEW

**Comment by hsadler** [comment]
Travis failed on this one.

**Comment by EricMFischer** [comment]
Travis tests are ago!

**Comment by cassiebeckley** [comment]
:+1:

**Comment by hsadler** [comment]
Thanks! +1

**Pull request merged**
